In [22]:
import numpy as np 

# 1. Create a 3x3x3 array with random values

In [23]:
np.random.rand(3,3,3)

array([[[0.7624815 , 0.5675531 , 0.63012308],
        [0.5961135 , 0.93328061, 0.74317853],
        [0.10948251, 0.58819123, 0.50820484]],

       [[0.32456314, 0.14021151, 0.62412428],
        [0.70153524, 0.50965685, 0.39385014],
        [0.59585362, 0.7222401 , 0.81149893]],

       [[0.0069635 , 0.71367119, 0.79045379],
        [0.81185921, 0.71280292, 0.11346527],
        [0.20370676, 0.44892857, 0.41927378]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [24]:
x= np.zeros((5,5))
print("The original matrix is : \n ",x)
x = np.diag([1,2,3,4],k=-1)
print("Final matrix is: \n",x)



The original matrix is : 
  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final matrix is: 
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


 # 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [25]:
x= np.zeros((8,8))

x[1::2,::2]=1 
x[::2,1::2]=1 
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

 # 4. Normalize a 5x5 random matrix

In [26]:
x = np.random.rand(5,5)
print("The original matrix  is :  \n",x)

x_norm= (x-x.min())/(x.max()-x.min())
print("Normalized matrix is : \n" ,x_norm)

The original matrix  is :  
 [[0.03327766 0.85984418 0.25369274 0.08965969 0.29775491]
 [0.74552651 0.60355976 0.00293785 0.62351396 0.59021   ]
 [0.09431489 0.22792928 0.08520896 0.02146762 0.61533284]
 [0.83187879 0.37201487 0.40258718 0.17745958 0.49003759]
 [0.98642482 0.12580657 0.11807124 0.70472146 0.1056457 ]]
Normalized matrix is : 
 [[0.03084923 0.87129404 0.25496514 0.08817792 0.29976713]
 [0.75505694 0.61070653 0.         0.63099577 0.59713263]
 [0.09291129 0.2287691  0.08365247 0.01884089 0.62267728]
 [0.8428591  0.37527393 0.40635956 0.17745201 0.49527828]
 [1.         0.12493173 0.11706652 0.71356676 0.10443235]]


# 5. How to find common values between two arrays?

In [27]:

x= np.array([1,2,7,9,3,4])
y= np.array([1,4,8,6,9])
for i in x :
    if i in y:
        print(i)
        


1
9
4


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
import datetime
 
today = datetime.date.today()
yesterday= today- datetime.timedelta(days = 1 )
tomorrow = today+ datetime.timedelta(days = 1)

print("yesterday: ",yesterday)
print("Today: ", today)
print("Tomorrow: ",tomorrow)

yesterday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31




# 7. Consider two random array A and B, check if they are equal

In [29]:
x= np.random.randint(1,3,3)
print(" First array x is : \n ",x)
y= np.random.randint(1,3,3)
print(" Second array y is : \n",y)
if np.allclose(x,y)== True:
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")


 First array x is : 
  [2 2 2]
 Second array y is : 
 [1 1 1]
Arrays are not equal.


 # 8.Create random vector of size 10 and replace the maximum value by 0

In [30]:
x= np.random.random(10)
print("The  original vector is: \n",x)
x[x.argmax()] = 0
print("After replace the max value by 0 , the vector is : \n",x)

The  original vector is: 
 [0.97916182 0.13866699 0.15737624 0.76239293 0.80391904 0.54984743
 0.90510703 0.88106894 0.76734816 0.53906682]
After replace the max value by 0 , the vector is : 
 [0.         0.13866699 0.15737624 0.76239293 0.80391904 0.54984743
 0.90510703 0.88106894 0.76734816 0.53906682]


# 9. How to print all the values of an array?

In [31]:
x= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
for i in x:
    print (i)

[1 2 3]
[4 5 6]
[7 8 9]


# 10.Subtract the mean of each row of a matrix

In [32]:
x = np.random.rand(5,5)
print("The matrix is : " , x)
y= x-x.mean()
print("final matrix is : ", y)            

The matrix is :  [[0.18362577 0.07259756 0.53696813 0.50187314 0.08328743]
 [0.67362512 0.36485223 0.91703185 0.85381859 0.84915643]
 [0.26485619 0.0384277  0.64648309 0.3164162  0.39043222]
 [0.52743211 0.47726549 0.79059967 0.59930777 0.20402955]
 [0.22201291 0.86382017 0.984632   0.05001321 0.36620607]]
final matrix is :  [[-0.28752505 -0.39855326  0.0658173   0.03072232 -0.3878634 ]
 [ 0.2024743  -0.10629859  0.44588103  0.38266777  0.3780056 ]
 [-0.20629463 -0.43272312  0.17533227 -0.15473462 -0.0807186 ]
 [ 0.05628129  0.00611466  0.31944884  0.12815694 -0.26712128]
 [-0.24913792  0.39266934  0.51348118 -0.42113762 -0.10494475]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector 
(be careful with repeated indices)?

In [33]:
Z = np.ones(10)
print("The first vector is: \n",Z)
I = np.random.randint(0,len(Z),20)
print("The second vector is :\n",I)
Z += np.bincount(I, minlength=len(Z))
print(Z)


The first vector is: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The second vector is :
 [3 3 0 7 2 9 5 2 2 8 4 4 3 7 8 5 7 1 4 6]
[2. 2. 4. 4. 4. 3. 2. 4. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [34]:
x= np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
y= np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
dot = x@y
print("Dot product is: \n",dot)
diagonal = np.diag(dot)
print("Diagonal of dot product is : \n" ,diagonal)

Dot product is: 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Diagonal of dot product is : 
 [ 30  81 150]


# 13.How to find the most frequent value in an array?

In [35]:

x= np.random.randint(0,10,5)
print("Array is : \n",x)
np.bincount(x).argmax()

Array is : 
 [9 1 1 7 5]


1

# 14.How to get the n largest values of an array

In [36]:
x= np.random.randint(0,20,10)
print("x is: \n ",x)

val = x[np.argsort(x)]
val= val[-1]

print("value is: \n", val)

x is: 
  [ 7  6  7  0  2  6 18  2 12 17]
value is: 
 18


# 15.How to create a record array from a regular array?


In [37]:
x = np.array([1,2,3,4,5,6,7,8,9])
print("Regular array is : \n",x)
y= np.core.records.fromarrays(x.T)
print("Record array is: \n",y)

Regular array is : 
 [1 2 3 4 5 6 7 8 9]
Record array is: 
 (1, 2, 3, 4, 5, 6, 7, 8, 9)
